[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

exclude = [
    "**/__pycache__",
    "build",
    "dist"
]
reportUnnecessaryTypeIgnoreComment = "warning"
pythonVersion = "3.8"
typeCheckingMode = "basic"