name: Feature request
about: Suggest an idea for this project
labels: ["Feature request"]
assignees: ''
body:
  - type: markdown
      attributes:
        value: |
          Thanks for taking the time to fill out this feature request!
  - type: input
    id: description
    attributes:
    label: Description
    description: >
      A short description of your idea
    validations:
    required: true
  - type: dropdown
    is: for-what
    attributes:
    multiple: false
    label: What is the feature request for?
    options:
      - disspy
      - The documentation
    validations:
    required: true
  - type: textarea
    id: the-problem
    attributes:
    label: The Problem
    description: >
      Your problem.
      Please try give some examples.
    validations:
    required: true